#!/bin/bash
WD=$PWD
rm -rf /root/xtream-ui-ubuntu
git clone git@github.com:Servextex/xtream-ui-ubuntu.git /root/xtream-ui-ubuntu
reprepro --keepunreferencedfiles -Vb /root/xtream-ui-ubuntu/package/Ubuntu/ includedeb jammy $1
cp /root/xtream-ui-ubuntu/package/Ubuntu/dists/jammy/Release /root/xtream-ui-ubuntu/package/Ubuntu/dists/jammy/InRelease
cd /root/xtream-ui-ubuntu/
git add *
git commit -m "add Ubuntu 22.04 packages"
git push -u origin main
cd $WD
rm -f $1
