#!/bin/bash
WD=$PWD
rm -rf /root/xtream-ui-ubuntu
git clone git@github.com:Servextex/xtream-ui-ubuntu.git /root/xtream-ui-ubuntu
reprepro --keepunreferencedfiles -Vb /root/xtream-ui-ubuntu/package/Ubuntu/ includedeb bionic $1
cp /root/xtream-ui-ubuntu/package/Ubuntu/dists/bionic/Release /root/xtream-ui-ubuntu/package/Ubuntu/dists/bionic/InRelease
cd /root/xtream-ui-ubuntu/
git add *
git commit -m "add Ubuntu 18.04 packages"
git push -u origin main
cd $WD
rm -rf $1
