#!/bin/bash
WD=$PWD
rm -rf /root/xtream-ui-ubuntu
git clone git@github.com:Servextex/xtream-ui-ubuntu.git /root/xtream-ui-ubuntu
reprepro --keepunreferencedfiles -Vb /root/xtream-ui-ubuntu/package/debian/ includedeb buster $1
cp /root/xtream-ui-ubuntu/package/debian/dists/buster/Release /root/xtream-ui-ubuntu/package/debian/dists/buster/InRelease
cd /root/xtream-ui-ubuntu/
git add *
git commit -m "add Debian 10 packages"
git push -u origin main
cd $WD
rm -f $1
