#!/bin/bash
rm -rf /root/xtream-ui-ubuntu
git clone git@github.com:Servextex/xtream-ui-ubuntu.git /root/xtream-ui-ubuntu
NAMERPM=$(rpm -pq --queryformat "%{NAME}" $1)
MINRPM=${NAMERPM::1}
mkdir -p /root/xtream-ui-ubuntu/package/Fedora/36/x86_64/Packages/$MINRPM
mv \$1 /root/xtream-ui-ubuntu/package/Fedora/36/x86_64/Packages/$MINRPM
createrepo --update /root/xtream-ui-ubuntu/package/Fedora/36/x86_64
cd /root/xtream-ui-ubuntu/
git add *
git commit -m "add Fedora 36 packages"
git push -u origin main
